<?xml version="1.0" encoding="utf-8"?><Database Name="bdTurnos" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.20.134\MSSQLSERVER2014;Initial Catalog=bdTurnos;Persist Security Info=True;User ID=sa" SettingsObjectName="turnosDashboard.Properties.Settings" SettingsPropertyName="bdTurnosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.caWeathers" Member="caWeathers">
    <Type Name="caWeathers">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="weather" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="fIns" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fact" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>