<?xml version="1.0" encoding="utf-8"?><Database Name="bdTurnos" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.20.134\MSSQLSERVER2014;Initial Catalog=bdTurnos;Persist Security Info=True;User ID=sa" SettingsObjectName="turnosAdministrator.Properties.Settings" SettingsPropertyName="bdTurnosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.caWeathers" Member="caWeathers">
    <Type Name="caWeathers">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="weather" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="fIns" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fact" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dePlayList" Member="dePlayList">
    <Type Name="dePlayList">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPlayList" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="videoPath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fIns" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fAct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="caPlayList_dePlayList" Member="caPlayList" ThisKey="idPlayList" OtherKey="id" Type="caPlayList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.caPlayList" Member="caPlayList">
    <Type Name="caPlayList">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="playListName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="totalVideos" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="fIns" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fAct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="defaultPL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="caPlayList_dePlayList" Member="dePlayList" ThisKey="id" OtherKey="idPlayList" Type="dePlayList" />
    </Type>
  </Table>
</Database>